### ISSUE TITLE
Feature; Stop/Start/Dock Roomba from the card

### ISSUE THREAD

**Issue by freemann** [athombv/com.thinkingcleaner#2]
Now its only possible to stop/start/dock a Roomba through a flow.
It would also really cool to stop/start/dock Roomba from its Card.

**Comment by jhaverkort** [comment]
Agreed !  I dont own a roomba yet.., but this is a must before buying one :)

**Comment by RobinBol** [comment]
This will be available in version 2.0.1. of the app.
