### ISSUE TITLE
Can't find my thinkingcleaner faceplate.

### ISSUE THREAD

**Issue by Vonkenboer** [athombv/com.thinkingcleaner#5]
My Roomba with the Thinking Cleaner faceplate is not found when adding the device.

I don't use the Thinking Cleaner mobile app and I blocked any internet access for the faceplate.
My Fibaro HC2 gateway does communicate with it, so it should be able to find it.

Does it need internet connection or the Thinking Cleaner mobile app to work?
If so, can you please add the ability to communicate on local LAN only and add an option to manually assign an ip-address.

Thanks in advance.

**Comment by RobinBol** [comment]
The Homey app for TC uses a service hosted by Thinking Bits to discover devices, therefore it needs access to the internet.

**Comment by Vonkenboer** [comment]
Please add LAN functionality with an option to assign IP-address manualy. Should be easy to do.
